// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GoldenLine.Desktop.Data;

#nullable disable

namespace GoldenLine.Desktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219132711_DropSiteLogs")]
    partial class DropSiteLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GoldenLine.Desktop.Models.DailyStatus", b =>
                {
                    b.Property<int>("DailyStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DailyStatusId");

                    b.HasIndex("PersonnelId", "Date")
                        .IsUnique();

                    b.ToTable("DailyStatuses");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Edge", b =>
                {
                    b.Property<string>("EdgeID")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HedefNodeID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("KaynakNodeID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("EdgeID");

                    b.HasIndex("ProjeID");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.EquipmentItem", b =>
                {
                    b.Property<int>("EquipmentItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltGrup")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnaGrup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AraGrup")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalibrationIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCalibrationRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KalemNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("KalemTanim")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokasyon")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OlcuAciklama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SayimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonKullanimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tedarikci")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UreticiKodu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UreticiKodu2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentItemID");

                    b.HasIndex("SupplierId");

                    b.ToTable("EquipmentItems");
                });
            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryAssignment", b =>
                {
                    b.Property<int>("InventoryAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Active");

                    b.HasKey("InventoryAssignmentId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("EquipmentItemId", "PersonnelId", "Status")
                        .HasDatabaseName("IX_Assignments_Item_Person_Status");

                    b.ToTable("InventoryAssignments");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryCountLine", b =>
                {
                    b.Property<int>("InventoryCountLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdjustmentMovementId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryCountSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryCountLineId");

                    b.HasIndex("AdjustmentMovementId");

                    b.HasIndex("EquipmentItemId");

                    b.HasIndex("InventoryCountSessionId");

                    b.ToTable("InventoryCountLines");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryCountSession", b =>
                {
                    b.Property<int>("InventoryCountSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open");

                    b.HasKey("InventoryCountSessionId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryCountSessions");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryLocation", b =>
                {
                    b.Property<int>("InventoryLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryLocationID");

                    b.ToTable("InventoryLocations");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryMovement", b =>
                {
                    b.Property<int>("InventoryMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryMovementId");

                    b.HasIndex("EquipmentItemId");

                    b.HasIndex("InventoryAssignmentId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventorySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventorySnapshots", (string)null);
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.ItemLocationStock", b =>
                {
                    b.Property<int>("ItemLocationStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemLocationStockId");

                    b.HasIndex("EquipmentItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("ItemLocationStocks");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Node", b =>
                {
                    b.Property<string>("NodeID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentNodeId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("X_Pozisyonu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Y_Pozisyonu")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("NodeID");

                    b.HasIndex("ParentNodeId");

                    b.HasIndex("ProjeID");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Personnel", b =>
                {
                    b.Property<int>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentProject")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryLocation")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Skills")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamOrProject")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonnelId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Project", b =>
                {
                    b.Property<int>("ProjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OlusturanKullanici")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonDuzenlemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SonDuzenleyenKullanici")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjeID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("SupplierId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.DailyStatus", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.Personnel", "Personnel")
                        .WithMany("DailyStatuses")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Edge", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.Project", "Project")
                        .WithMany("Edges")
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.EquipmentItem", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.Supplier", "Supplier")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryAssignment", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenLine.Desktop.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentItem");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryCountLine", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.InventoryMovement", "AdjustmentMovement")
                        .WithMany()
                        .HasForeignKey("AdjustmentMovementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoldenLine.Desktop.Models.EquipmentItem", "EquipmentItem")
                        .WithMany()
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenLine.Desktop.Models.InventoryCountSession", "Session")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryCountSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdjustmentMovement");

                    b.Navigation("EquipmentItem");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryCountSession", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryMovement", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("Movements")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenLine.Desktop.Models.InventoryAssignment", "InventoryAssignment")
                        .WithMany("Movements")
                        .HasForeignKey("InventoryAssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GoldenLine.Desktop.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquipmentItem");

                    b.Navigation("InventoryAssignment");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.ItemLocationStock", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("LocationStocks")
                        .HasForeignKey("EquipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenLine.Desktop.Models.Location", "Location")
                        .WithMany("ItemLocationStocks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentItem");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Node", b =>
                {
                    b.HasOne("GoldenLine.Desktop.Models.Node", "ParentNode")
                        .WithMany("ChildNodes")
                        .HasForeignKey("ParentNodeId");

                    b.HasOne("GoldenLine.Desktop.Models.Project", "Project")
                        .WithMany("Nodes")
                        .HasForeignKey("ProjeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentNode");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.EquipmentItem", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("LocationStocks");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryAssignment", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.InventoryCountSession", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Location", b =>
                {
                    b.Navigation("ItemLocationStocks");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Node", b =>
                {
                    b.Navigation("ChildNodes");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Personnel", b =>
                {
                    b.Navigation("DailyStatuses");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Project", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("GoldenLine.Desktop.Models.Supplier", b =>
                {
                    b.Navigation("EquipmentItems");
                });
#pragma warning restore 612, 618
        }
    }
}

