// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using GoldenLine.Desktop.Data;

#nullable disable

namespace GoldenLine.Desktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251230190000_AddLogisticsTables")]
    partial class AddLogisticsTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
#pragma warning restore 612, 618
        }
    }
}

